### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rlouch2**
Added ability to checkin/checkout from the wrapper

### CODE REVIEW

**Comment by StarRezDev** [comment]
Thanks for the PR, unfortunately it looks like the tabs in the CS file have been replaced with spaces, which makes the diff hard to read. Please use tabs for this project.

Also, its not a good idea to commit snk files to public repositories. We have a build of this project on our build server that strong names the DLL and uploads it to Nuget, so you should be able to use that if you need a strong named version, once this PR is merged.

**Comment by rlouch2** [comment]
There I removed the .snk files (oops!)...

I also changed the spaces to tabs for the StarRezApiClient file.  See if that looks any better.

**Comment by StarRezDev** [comment]
The indents look better, thanks. It does look like the legacy authentication is now the only one supported though, which is not ideal, and there seems to be some unused code related to reports in there. Perhaps you need to rebase your changes on the latest master branch?

**Comment by StarRezDev** [comment]
That looks much better, though the build is failing because the snk files are still referenced in the project file. If you fix that up, I'll merge the PR and then the new functionality should be available from Nuget

**Comment by rlouch2** [comment]
Bah, sorry I don't use git that much and it takes me a bit to remember how to use it! Those references have been removed now, I think we should be good to go!

**Pull request merged**
